/* https://www.hackerrank.com/challenges/weather-observation-station-5/problem */

SELECT CITY, LENGTH(CITY) AS LONGEST_CITY 
FROM STATION 
ORDER BY LONGEST_CITY DESC, CITY ASC LIMIT 1;

SELECT CITY, LENGTH(CITY) AS SHORTEST_CITY 
FROM STATION 
ORDER BY SHORTEST_CITY ASC, CITY ASC LIMIT 1;
